### ISSUE TITLE
Missing functionality: Filter out duplicates, paragraph format instead of list format, copy output with included line breaks

### ISSUE THREAD

**Issue by kori228** [CollinBrennan/word-generator#2]
1. Missing functionality from previous site where you could filter out duplicates to create only novel words.

2. Conversely, also missing functionality from previous site to generate as a paragraph instead of a list to emulate a piece of text written with the generated words

3. Missing functionality to copy output with included line breaks. While it displays on the site as a list format, it won't paste into a spreadsheet as separate entries.

**Comment by CollinBrennan** [comment]
This functionality is planned to be implemented. What format(s) of the word list would you ideally like to have when clicking the copy button?

**Comment by kori228** [comment]
the commit has resolved the issues listed, thanks. 

basically on the previous version without the specific List format and Copy button, I would have to highlight-drag to copy, and pasting this into Google Spreadsheets or Microsoft Excel, would put it all in one cell rather than separate entries. The implemented List format and Copy button work as requested now.
