### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by HangryOpossum** [CollinBrennan/word-generator#3]
So I used GenGo for a while (Thank you for making it, saved me a lot of time) and just saw it has been moved to Wrdz and most of what I have doesn't work with this new version as it is missing filters and the extra [ bracket. I don't know if I am just bad at looking on the "how to" part on here or the generator itself but I can't seem to find them. Like with my conlang has a complex pattern and filter list which in order to get it to work on here I might as well do it manually without the generator. Like I used to have a pattern like -[B(D) S(C)]V[(C)(C)(C) (D)(D)(D)].([D C])V[(C)(C)(C) (D)(D)(D)].-, I added the - . just to make it easier to read for my own sake and I always chose the max syllable as 1 for this to work though. I also had something like 450 filters. So I don't know if these features have been missed off, in the works or if there is a new way to do it that I am not aware of, either way I just thought I would say.

**Comment by CollinBrennan** [comment]
Filters have been renamed to 'exceptions' on this version of the app and I do plan on adding brackets. Sorry for the inconvenience at the moment.

**Comment by HangryOpossum** [comment]
> Filters have been renamed to 'exceptions' on this version of the app and I do plan on adding brackets. Sorry for the inconvenience at the moment.

Oh right okay, sorry with the word "exceptions" I assumed they were things that went against filters and patterns. Oh right well glad they are being added and no worries, I just wanted to know what was happening. Thank you for your reply and generator.
