### ISSUE TITLE
Some more missing features

### ISSUE THREAD

**Issue by Descendit-Bear** [CollinBrennan/word-generator#4]
On Gen-Go, you were able to control the chance of every phoneme with an asterisk:

ɒʌ*6,

I would analyse phonetic transcriptions of real languages, find the percentage change of phonemes appearing in onsets, mindsets and offsets, and then apply those numbers to the generator. Wrdz seemingly doesn't recognise these.

 Has this feature been dropped? Is there another way I can do this in Wrdz?

**Comment by CreatureConstruct** [comment]
This would be a great feature to reintroduce.

**Comment by CollinBrennan** [comment]
There is no way to do this currently but it is planned!
