### ISSUE TITLE
Saving Work

### ISSUE THREAD

**Issue by CreatureConstruct** [CollinBrennan/word-generator#5]
There should be one text box for character groups and one for rewrites, like in GenGo. Having every single rewrite and character group split up into separate text boxes is super tedious, especially when you have to rewrite tons of information because leaving the page/refreshing/shutting down your pc loses all information. If there was a way to save all of your information like a template, this would be much more manageable. In GenGo it was easier to copy and paste information over from a google doc. Other than that, I've been using GenGo/Wrdz for years now and I love it. Definitely the best conlang generator.

**Comment by CollinBrennan** [comment]
I appreciate your comments! The separate inputs for character groups and rewrites was intended to make the generator easier to use. I plan on adding the ability to save your work in the future. I've been really busy with school and trying to find a job but I will hopefully return to this project soon!

**Comment by sivadjydnar** [comment]
This is the best word generator that I've come across in terms of ease of use.  The lack of a save feature would surely be nice though.  I spent a fair amount of time tweaking everything, only to lose it all when I clicked on 'Docs' looking for an answer to another question.  I hope you get around to adding some sort of save feature ;-)  as that would be great.  Thanks for the algorithm. +!
